# Generated by Django 2.0.9 on 2019-04-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dajia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
    ]
